org.gradle.jvmargs = -Xmx2G
org.gradle.configureondemand=true
targetJavaVersion = 25

# mod base properties
modName = ElyOff
modDescription = Press jump while gliding to cancel elytra flight. Server-side authoritative with an automatic client-side fallback.
modid = elyoff
modLicense = MIT
mavenGroup = io.github.unperage.elyoff

# fabric default dependencies property
loaderVersion = 0.19.3
loomVersion = 1.17-SNAPSHOT
